'use client';

import { useState, useCallback, useRef } from 'react';
import {
  QrCode, Loader2, ScanLine, Wifi, Radio, Cpu,
  ChevronRight, ChevronLeft, Check, ArrowRight, Copy,
  Smartphone, Zap, ExternalLink, Settings2, Shield,
  Signal, Lock, Unlock, RefreshCw, CircleCheck, CircleX, Info
} from 'lucide-react';
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogHeader,
  DialogTitle,
} from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';
import { Badge } from '@/components/ui/badge';
import { useAppStore } from '@/lib/store';
import type { Device } from '@/lib/types';
import { QrScanner } from '@/components/iot/qr/qr-scanner';

interface AddDeviceDialogProps {
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

type Step = 'scan' | 'info' | 'wifi' | 'done';

// What the QR on the physical device contains (generated BY the ESP32)
interface DeviceQrPayload {
  type?: string;
  deviceId: string;
  secret: string;
  apSsid?: string;
}

export function AddDeviceDialog({ open, onOpenChange }: AddDeviceDialogProps) {
  const { addDevice } = useAppStore();
  const scannerActiveRef = useRef(false);

  // Wizard state
  const [step, setStep] = useState<Step>('scan');
  const [isLoading, setIsLoading] = useState(false);
  const [error, setError] = useState('');

  // Device identity (from QR scan or manual entry)
  const [deviceId, setDeviceId] = useState('');
  const [secret, setSecret] = useState('');
  const [apSsid, setApSsid] = useState('');

  // QR scanner state
  const [scanning, setScanning] = useState(false);

  // Device info
  const [name, setName] = useState('');
  const [location, setLocation] = useState('');

  // WiFi configuration (to send to ESP32)
  const [wifiSsid, setWifiSsid] = useState('');
  const [wifiPassword, setWifiPassword] = useState('');
  const [mqttBroker, setMqttBroker] = useState('');
  const [mqttPort, setMqttPort] = useState('1883');
  const [wifiConfigSent, setWifiConfigSent] = useState<'idle' | 'sending' | 'success' | 'failed'>('idle');
  const [skipWifi, setSkipWifi] = useState(false);

  const registerDevice = async (): Promise<void> => {
    setIsLoading(true);
    setError('');
    try {
      const res = await fetch('/api/devices/register', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          deviceId,
          secret,
          name: name.trim(),
          location: location.trim() || undefined,
          wifiSsid: wifiSsid.trim() || undefined,
          wifiPassword: wifiPassword.trim() || undefined,
        }),
      });
      const responseData = await res.json();
      if (!res.ok) {
        throw new Error(responseData.error || 'Failed to register device');
      }
      addDevice(responseData.device as Device);
      setStep('done');
    } catch (err: unknown) {
      setError(err instanceof Error ? err.message : 'Network error');
    } finally {
      setIsLoading(false);
    }
  };

  // Try to send WiFi config directly to the ESP32 via its AP mode
  const sendWifiConfigToESP32 = async (): Promise<boolean> => {
    if (!wifiSsid.trim() || !mqttBroker.trim()) return false;

    setWifiConfigSent('sending');
    try {
      // The ESP32's AP IP is always 192.168.4.1 when in AP mode
      // This only works if the user is connected to the ESP32's AP network
      const esp32Url = 'http://192.168.4.1/config';
      const response = await fetch(esp32Url, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          type: 'iot-provisioning',
          version: 1,
          deviceId,
          secret,
          wifiSsid: wifiSsid.trim(),
          wifiPassword: wifiPassword.trim(),
          mqttBroker: mqttBroker.trim(),
          mqttPort: parseInt(mqttPort) || 1883,
          mqttWsPort: 3003,
        }),
        signal: AbortSignal.timeout(8000), // 8s timeout
      });

      if (response.ok) {
        setWifiConfigSent('success');
        return true;
      }
      setWifiConfigSent('failed');
      return false;
    } catch {
      // Expected to fail if not connected to ESP32's AP
      setWifiConfigSent('failed');
      return false;
    }
  };

  const handleQrScan = useCallback((data: string) => {
    try {
      const parsed: DeviceQrPayload = JSON.parse(data);
      if (parsed.deviceId && parsed.secret) {
        setDeviceId(parsed.deviceId);
        setSecret(parsed.secret);
        if (parsed.apSsid) setApSsid(parsed.apSsid);
        setScanning(false);
        scannerActiveRef.current = false;
        setStep('info');
      } else {
        setError('QR code does not contain valid device info (missing deviceId or secret)');
      }
    } catch {
      if (data.trim().length > 3) {
        setDeviceId(data.trim());
        setScanning(false);
        scannerActiveRef.current = false;
        setStep('info');
      } else {
        setError('Invalid QR code format');
      }
    }
  }, []);

  const handleQrScanError = useCallback((err: string) => {
    console.error('QR scan error:', err);
  }, []);

  const handleManualEntry = () => {
    if (!deviceId.trim() || !secret.trim()) {
      setError('Device ID and Secret are required');
      return;
    }
    setError('');
    setStep('info');
  };

  const handleInfoNext = () => {
    if (!name.trim()) {
      setError('Device name is required');
      return;
    }
    setError('');
    setStep('wifi');
  };

  const handleWifiNext = async () => {
    if (!skipWifi && !wifiSsid.trim()) {
      setError('WiFi SSID is required (or skip this step)');
      return;
    }
    setError('');

    // If user provided WiFi config, try sending to ESP32 first
    if (!skipWifi && wifiSsid.trim() && mqttBroker.trim()) {
      await sendWifiConfigToESP32();
    }

    // Then register the device in our database
    await registerDevice();
  };

  const handleClose = () => {
    setError('');
    setStep('scan');
    setDeviceId('');
    setSecret('');
    setApSsid('');
    setName('');
    setLocation('');
    setScanning(false);
    setWifiSsid('');
    setWifiPassword('');
    setMqttBroker('');
    setMqttPort('1883');
    setWifiConfigSent('idle');
    setSkipWifi(false);
    scannerActiveRef.current = false;
    onOpenChange(false);
  };

  const stepOrder: Step[] = ['scan', 'info', 'wifi', 'done'];
  const currentStepIndex = stepOrder.indexOf(step);

  return (
    <Dialog open={open} onOpenChange={(isOpen) => { if (!isOpen) handleClose(); else onOpenChange(true); }}>
      <DialogContent className="sm:max-w-lg max-h-[90vh] overflow-y-auto">
        <DialogHeader>
          <DialogTitle className="flex items-center gap-2">
            <Cpu className="h-5 w-5 text-emerald-500" />
            Add New Device
          </DialogTitle>
          <DialogDescription>
            Scan the QR code from your ESP32 to register it
          </DialogDescription>
        </DialogHeader>

        {/* Step Progress Bar */}
        {step !== 'done' && (
          <div className="flex items-center gap-1 mb-2">
            {stepOrder.slice(0, -1).map((s, i) => (
              <div key={s} className="flex items-center flex-1">
                <div className={`h-1.5 flex-1 rounded-full transition-all duration-300 ${
                  i <= currentStepIndex ? 'bg-emerald-500' : 'bg-muted'
                }`} />
              </div>
            ))}
          </div>
        )}

        {/* Step labels */}
        {step !== 'done' && (
          <div className="flex justify-between text-[11px] sm:text-xs text-muted-foreground -mt-1 mb-1">
            <span className={currentStepIndex >= 0 ? 'text-emerald-600 dark:text-emerald-400 font-medium' : ''}>Scan</span>
            <span className={currentStepIndex >= 1 ? 'text-emerald-600 dark:text-emerald-400 font-medium' : ''}>Details</span>
            <span className={currentStepIndex >= 2 ? 'text-emerald-600 dark:text-emerald-400 font-medium' : ''}>WiFi</span>
          </div>
        )}

        {/* ─── Step 1: Scan QR ─────────────────────────────────── */}
        {step === 'scan' && (
          <div className="space-y-4">
            {/* Explanation of how the ESP32 QR works */}
            <div className="p-3 rounded-lg bg-emerald-500/10 border border-emerald-500/20 space-y-2">
              <div className="flex items-center gap-2">
                <Smartphone className="h-4 w-4 text-emerald-600 dark:text-emerald-400 shrink-0" />
                <p className="text-sm font-medium text-emerald-600 dark:text-emerald-400">
                  The QR code is on your ESP32
                </p>
              </div>
              <div className="space-y-1.5 text-xs text-muted-foreground">
                <p>Your ESP32 generates its own unique QR code when it starts up. Here&apos;s how to find it:</p>
                <ol className="list-decimal list-inside space-y-1 ml-1">
                  <li>Power on your ESP32 (it starts in setup mode)</li>
                  <li>From a computer, connect to WiFi: <Badge variant="outline" className="text-[10px] font-mono ml-1">IoT-ESP32-XXXX</Badge></li>
                  <li>Open <code className="bg-muted px-1.5 py-0.5 rounded font-mono text-[10px]">http://192.168.4.1</code> in your browser</li>
                  <li>You&apos;ll see the QR code — print it or display it on screen</li>
                  <li>Scan it below with your phone camera 👇</li>
                </ol>
              </div>
            </div>

            {!scanning ? (
              <div className="flex flex-col items-center justify-center py-6 space-y-4">
                <div className="w-24 h-24 rounded-full bg-emerald-500/10 flex items-center justify-center">
                  <ScanLine className="h-12 w-12 text-emerald-500" />
                </div>
                <div className="text-center space-y-1">
                  <p className="text-sm font-medium">Ready to Scan</p>
                  <p className="text-xs text-muted-foreground">
                    Point your camera at the QR code on your ESP32
                  </p>
                </div>
                <Button
                  onClick={() => { setScanning(true); scannerActiveRef.current = true; }}
                  className="bg-emerald-600 hover:bg-emerald-700 text-white"
                  size="lg"
                >
                  <QrCode className="h-5 w-5 mr-2" />
                  Start Scanning
                </Button>
              </div>
            ) : (
              <div className="space-y-3">
                <QrScanner
                  onScan={handleQrScan}
                  onError={handleQrScanError}
                  onClose={() => { setScanning(false); scannerActiveRef.current = false; }}
                />
              </div>
            )}

            {/* Manual entry fallback */}
            <div className="relative">
              <div className="absolute inset-0 flex items-center">
                <span className="w-full border-t" />
              </div>
              <div className="relative flex justify-center text-xs uppercase">
                <span className="bg-background px-2 text-muted-foreground">or enter manually</span>
              </div>
            </div>

            <div className="space-y-3">
              <div className="space-y-1.5">
                <Label htmlFor="manual-device-id" className="text-xs">Device ID</Label>
                <Input
                  id="manual-device-id"
                  placeholder="e.g., ESP32-ABC123"
                  value={deviceId}
                  onChange={(e) => setDeviceId(e.target.value)}
                  className="font-mono text-sm"
                />
              </div>
              <div className="space-y-1.5">
                <Label htmlFor="manual-secret" className="text-xs">Device Secret</Label>
                <Input
                  id="manual-secret"
                  type="password"
                  placeholder="Secret key from ESP32 Serial output"
                  value={secret}
                  onChange={(e) => setSecret(e.target.value)}
                  className="font-mono text-sm"
                />
              </div>
              <p className="text-[10px] text-muted-foreground">
                Find these in the Arduino Serial Monitor (115200 baud) or on the ESP32&apos;s web page at <code className="bg-muted px-1 rounded">192.168.4.1</code>
              </p>
              {error && <p className="text-xs text-destructive">{error}</p>}
              <Button
                onClick={handleManualEntry}
                disabled={!deviceId.trim() || !secret.trim()}
                className="w-full"
                variant="outline"
              >
                Continue with Manual Entry
                <ChevronRight className="h-4 w-4 ml-1" />
              </Button>
            </div>
          </div>
        )}

        {/* ─── Step 2: Device Info ────────────────────────────── */}
        {step === 'info' && (
          <div className="space-y-4">
            <div className="p-3 rounded-lg bg-emerald-500/10 border border-emerald-500/20">
              <div className="flex items-center gap-2">
                <Check className="h-4 w-4 text-emerald-500" />
                <p className="text-sm font-medium text-emerald-600 dark:text-emerald-400">Device Identified</p>
              </div>
              <div className="grid grid-cols-1 sm:grid-cols-2 gap-2 mt-2 text-xs">
                <div>
                  <span className="text-muted-foreground">Device ID:</span>
                  <p className="font-mono font-medium">{deviceId}</p>
                </div>
                <div>
                  <span className="text-muted-foreground">Secret:</span>
                  <p className="font-mono font-medium">{secret.slice(0, 8)}•••</p>
                </div>
              </div>
            </div>

            <div className="space-y-3">
              <div className="space-y-1.5">
                <Label htmlFor="device-name">Device Name *</Label>
                <Input
                  id="device-name"
                  placeholder="e.g., Workshop Sensor, Office Monitor"
                  value={name}
                  onChange={(e) => setName(e.target.value)}
                  autoFocus
                />
              </div>
              <div className="space-y-1.5">
                <Label htmlFor="device-location">Location / Zone</Label>
                <Input
                  id="device-location"
                  placeholder="e.g., Building A, Floor 2, Zone 3"
                  value={location}
                  onChange={(e) => setLocation(e.target.value)}
                />
              </div>
            </div>

            {error && <p className="text-xs text-destructive">{error}</p>}

            <div className="flex flex-col-reverse sm:flex-row gap-2 sm:justify-end">
              <Button variant="outline" onClick={() => { setError(''); setStep('scan'); }}>
                <ChevronLeft className="h-4 w-4 mr-1" />
                Back
              </Button>
              <Button
                onClick={handleInfoNext}
                disabled={!name.trim()}
                className="bg-emerald-600 hover:bg-emerald-700 text-white"
              >
                Next: Configure WiFi
                <ChevronRight className="h-4 w-4 ml-1" />
              </Button>
            </div>
          </div>
        )}

        {/* ─── Step 3: WiFi Configuration ────────────────────── */}
        {step === 'wifi' && (
          <div className="space-y-4">
            <div className="p-3 rounded-lg bg-teal-500/10 border border-teal-500/20 space-y-2">
              <div className="flex items-center gap-2">
                <Wifi className="h-4 w-4 text-teal-600 dark:text-teal-400 shrink-0" />
                <p className="text-sm font-medium text-teal-600 dark:text-teal-400">
                  Configure WiFi &amp; MQTT
                </p>
              </div>
              <p className="text-xs text-muted-foreground">
                Your ESP32 needs WiFi credentials and an MQTT broker address to start sending sensor data.
                You can configure this now or later from the ESP32&apos;s AP page.
              </p>
            </div>

            {/* Option A: Configure now */}
            {!skipWifi && (
              <div className="space-y-3">
                <div className="space-y-1.5">
                  <Label htmlFor="wifi-ssid" className="text-xs flex items-center gap-1">
                    <Signal className="h-3 w-3" />
                    WiFi Network Name (SSID) *
                  </Label>
                  <Input
                    id="wifi-ssid"
                    placeholder="Your WiFi name"
                    value={wifiSsid}
                    onChange={(e) => setWifiSsid(e.target.value)}
                    autoFocus
                  />
                </div>
                <div className="space-y-1.5">
                  <Label htmlFor="wifi-pass" className="text-xs flex items-center gap-1">
                    <Lock className="h-3 w-3" />
                    WiFi Password
                  </Label>
                  <Input
                    id="wifi-pass"
                    type="password"
                    placeholder="Your WiFi password"
                    value={wifiPassword}
                    onChange={(e) => setWifiPassword(e.target.value)}
                  />
                </div>
                <div className="space-y-1.5">
                  <Label htmlFor="mqtt-broker" className="text-xs flex items-center gap-1">
                    <Radio className="h-3 w-3" />
                    MQTT Broker Address *
                  </Label>
                  <Input
                    id="mqtt-broker"
                    placeholder="e.g., 192.168.1.100 or broker.example.com"
                    value={mqttBroker}
                    onChange={(e) => setMqttBroker(e.target.value)}
                  />
                  <p className="text-[10px] text-muted-foreground">
                    The IP address or hostname where your MQTT broker is running
                  </p>
                </div>
                <div className="space-y-1.5">
                  <Label htmlFor="mqtt-port" className="text-xs">MQTT Port</Label>
                  <Input
                    id="mqtt-port"
                    type="number"
                    placeholder="1883"
                    value={mqttPort}
                    onChange={(e) => setMqttPort(e.target.value)}
                    className="max-w-[120px]"
                  />
                </div>

                {/* Status of sending config to ESP32 */}
                {wifiConfigSent === 'sending' && (
                  <div className="flex items-center gap-2 p-2 rounded-lg bg-muted text-xs">
                    <Loader2 className="h-3 w-3 animate-spin text-emerald-500" />
                    <span>Sending configuration to ESP32...</span>
                  </div>
                )}
                {wifiConfigSent === 'success' && (
                  <div className="flex items-center gap-2 p-2 rounded-lg bg-emerald-500/10 border border-emerald-500/20 text-xs">
                    <CircleCheck className="h-4 w-4 text-emerald-500" />
                    <span className="text-emerald-600 dark:text-emerald-400">Configuration sent to ESP32! It will restart and connect.</span>
                  </div>
                )}
                {wifiConfigSent === 'failed' && (
                  <div className="p-2 rounded-lg bg-amber-500/10 border border-amber-500/20 space-y-1">
                    <div className="flex items-start gap-2 text-xs">
                      <Info className="h-3.5 w-3.5 text-amber-500 mt-0.5 shrink-0" />
                      <div>
                        <p className="text-amber-600 dark:text-amber-400 font-medium">Could not reach ESP32 directly</p>
                        <p className="text-muted-foreground mt-0.5">
                          To send config to ESP32, connect your phone/computer to the ESP32&apos;s WiFi network
                          (<span className="font-mono">{apSsid || `IoT-${deviceId}`}</span>),
                          then open <code className="bg-muted px-1 rounded text-[10px]">192.168.4.1</code> and enter the WiFi details there.
                        </p>
                      </div>
                    </div>
                  </div>
                )}
              </div>
            )}

            {/* Skip WiFi option */}
            <div className="relative">
              <div className="absolute inset-0 flex items-center">
                <span className="w-full border-t" />
              </div>
              <div className="relative flex justify-center text-xs">
                <button
                  type="button"
                  onClick={() => { setSkipWifi(!skipWifi); setError(''); }}
                  className="bg-background px-2 text-muted-foreground hover:text-foreground transition-colors"
                >
                  {skipWifi ? 'Configure WiFi now' : 'Skip & configure later'}
                </button>
              </div>
            </div>

            {skipWifi && (
              <div className="p-3 rounded-lg bg-muted/50 space-y-2 text-xs">
                <p className="font-medium">You can configure WiFi later:</p>
                <ol className="text-muted-foreground space-y-1 list-decimal list-inside">
                  <li>Connect to ESP32&apos;s WiFi: <code className="bg-muted px-1 rounded font-mono text-[10px]">{apSsid || `IoT-${deviceId}`}</code></li>
                  <li>Open <code className="bg-muted px-1 rounded font-mono text-[10px]">192.168.4.1</code> in your browser</li>
                  <li>Enter your WiFi &amp; MQTT broker details</li>
                  <li>Or use Serial Monitor: <code className="bg-muted px-1 rounded font-mono text-[10px]">PROVISION {"{...}"}</code></li>
                </ol>
              </div>
            )}

            {error && <p className="text-xs text-destructive">{error}</p>}

            <div className="flex flex-col-reverse sm:flex-row gap-2 sm:justify-end">
              <Button variant="outline" onClick={() => { setError(''); setStep('info'); }}>
                <ChevronLeft className="h-4 w-4 mr-1" />
                Back
              </Button>
              <Button
                onClick={handleWifiNext}
                disabled={isLoading || (!skipWifi && !wifiSsid.trim())}
                className="bg-emerald-600 hover:bg-emerald-700 text-white"
              >
                {isLoading ? (
                  <>
                    <Loader2 className="mr-2 h-4 w-4 animate-spin" />
                    Registering...
                  </>
                ) : (
                  <>
                    <Zap className="mr-2 h-4 w-4" />
                    Register Device
                  </>
                )}
              </Button>
            </div>
          </div>
        )}

        {/* ─── Step 4: Done ───────────────────────────────────── */}
        {step === 'done' && (
          <div className="flex flex-col items-center justify-center py-8 space-y-4">
            <div className="w-20 h-20 rounded-full bg-emerald-500/20 flex items-center justify-center">
              <Check className="h-10 w-10 text-emerald-500" />
            </div>
            <div className="text-center space-y-1">
              <p className="text-lg font-semibold">Device Registered!</p>
              <p className="text-sm text-muted-foreground">
                <strong>{name}</strong> has been added to your dashboard.
              </p>
            </div>
            <div className="flex flex-wrap gap-2 justify-center">
              <Badge variant="outline" className="text-xs">
                <Cpu className="h-3 w-3 mr-1" />
                {deviceId}
              </Badge>
              {location && (
                <Badge variant="outline" className="text-xs">
                  {location}
                </Badge>
              )}
            </div>

            {/* Status & next steps */}
            <div className="w-full p-3 rounded-lg bg-muted/50 space-y-3 text-xs">
              {wifiConfigSent === 'success' ? (
                <>
                  <div className="flex items-center gap-2 text-emerald-600 dark:text-emerald-400 font-medium">
                    <CircleCheck className="h-4 w-4" />
                    WiFi &amp; MQTT configured!
                  </div>
                  <p className="text-muted-foreground">
                    Your ESP32 is restarting and will connect to your WiFi. Sensor data will start appearing
                    in the dashboard within 30 seconds.
                  </p>
                </>
              ) : (
                <>
                  <div className="flex items-center gap-2 font-medium">
                    <Settings2 className="h-4 w-4 text-amber-500" />
                    WiFi configuration needed
                  </div>
                  <p className="text-muted-foreground">
                    To start receiving data, configure WiFi &amp; MQTT on your ESP32:
                  </p>
                  <ol className="text-muted-foreground space-y-1.5 list-decimal list-inside">
                    <li>
                      Connect to ESP32&apos;s WiFi: <code className="bg-muted px-1 rounded font-mono text-[10px]">{apSsid || `IoT-${deviceId}`}</code>
                    </li>
                    <li>
                      Open <code className="bg-muted px-1 rounded font-mono text-[10px]">192.168.4.1</code> and enter your WiFi &amp; MQTT broker
                    </li>
                    <li>ESP32 will restart, connect to WiFi, and data will appear automatically!</li>
                  </ol>
                </>
              )}
            </div>

            <Button onClick={handleClose} className="bg-emerald-600 hover:bg-emerald-700 text-white">
              Done
            </Button>
          </div>
        )}
      </DialogContent>
    </Dialog>
  );
}
