'use client';

import { useEffect, useRef, useState } from 'react';
import QRCode from 'qrcode';
import { Download, Copy, Check, Printer, QrCode } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Label } from '@/components/ui/label';

interface DeviceQrPayload {
  type: 'iot-device';
  deviceId: string;
  secret: string;
  apSsid: string;
}

interface QrGeneratorProps {
  deviceId: string;
  secret: string;
  onClose?: () => void;
}

/**
 * Reprints the QR code for a registered device.
 * The original QR was generated by the ESP32 on first boot.
 * Use this if you lost the sticker and need to print a new one.
 * The QR contains the device identity (deviceId + secret + apSsid).
 * When scanned in the app, it triggers the "Add Device" wizard.
 */
export function QrGenerator({ deviceId, secret }: QrGeneratorProps) {
  const canvasRef = useRef<HTMLCanvasElement>(null);
  const [qrDataUrl, setQrDataUrl] = useState<string>('');
  const [copied, setCopied] = useState(false);

  const apSsid = `IoT-${deviceId}`;

  const payload: DeviceQrPayload = {
    type: 'iot-device',
    deviceId,
    secret,
    apSsid,
  };

  const payloadJson = JSON.stringify(payload, null, 2);

  // Generate QR code
  useEffect(() => {
    const generateQr = async () => {
      try {
        const dataUrl = await QRCode.toDataURL(JSON.stringify(payload), {
          width: 320,
          margin: 3,
          color: { dark: '#000000', light: '#ffffff' },
          errorCorrectionLevel: 'M',
        });
        setQrDataUrl(dataUrl);

        if (canvasRef.current) {
          const ctx = canvasRef.current.getContext('2d');
          if (ctx) {
            const img = new Image();
            img.onload = () => {
              if (!canvasRef.current) return;
              canvasRef.current.width = 320;
              canvasRef.current.height = 320;
              ctx.drawImage(img, 0, 0, 320, 320);
            };
            img.src = dataUrl;
          }
        }
      } catch (err) {
        console.error('QR generation error:', err);
      }
    };
    generateQr();
  }, [deviceId, secret]);

  const handleCopyPayload = () => {
    navigator.clipboard.writeText(payloadJson).then(() => {
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    });
  };

  const handleDownload = () => {
    if (!qrDataUrl) return;
    const link = document.createElement('a');
    link.download = `${deviceId}-qr-sticker.png`;
    link.href = qrDataUrl;
    link.click();
  };

  const handlePrint = () => {
    if (!qrDataUrl) return;
    const printWindow = window.open('', '_blank');
    if (!printWindow) return;
    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>QR Sticker - ${deviceId}</title>
        <style>
          @page { size: 80mm 50mm; margin: 2mm; }
          body { margin: 0; padding: 4mm; font-family: monospace; text-align: center; }
          img { width: 35mm; height: 35mm; image-rendering: pixelated; }
          .id { font-size: 8pt; margin-top: 2mm; font-weight: bold; }
          .ap { font-size: 6pt; color: #666; }
        </style>
      </head>
      <body>
        <img src="${qrDataUrl}" alt="QR Code" />
        <div class="id">${deviceId.replace(/[<>&"']/g, c => ({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&#39;'}[c] || c))}</div>
        <div class="ap">AP: ${apSsid}</div>
        <script>window.onload=function(){window.print();}</script>
      </body>
      </html>
    `);
    printWindow.document.close();
  };

  return (
    <div className="space-y-4">
      <div className="flex items-center gap-2 p-3 rounded-lg bg-emerald-500/10 border border-emerald-500/20">
        <QrCode className="h-5 w-5 text-emerald-500 shrink-0" />
        <div>
          <p className="text-sm font-medium text-emerald-600 dark:text-emerald-400">
            Device QR Sticker
          </p>
          <p className="text-xs text-muted-foreground">
            Reprint this QR sticker for your ESP32 enclosure. The original was generated by the ESP32 at <code className="bg-muted px-1 rounded">192.168.4.1</code>.
          </p>
        </div>
      </div>

      {/* QR Code Display */}
      <div className="flex flex-col items-center space-y-3">
        <div className="p-4 bg-white rounded-xl shadow-sm border max-w-full overflow-hidden">
          <canvas ref={canvasRef} className="block max-w-full h-auto" style={{ width: 'min(240px, 100%)', height: 'auto', aspectRatio: '1/1' }} />
        </div>
        <p className="text-xs font-mono text-muted-foreground">{deviceId}</p>

        <div className="flex flex-wrap gap-2 justify-center">
          <Button variant="outline" size="sm" onClick={handleDownload} disabled={!qrDataUrl}>
            <Download className="h-3.5 w-3.5 mr-1.5" />
            Download
          </Button>
          <Button variant="outline" size="sm" onClick={handlePrint} disabled={!qrDataUrl}>
            <Printer className="h-3.5 w-3.5 mr-1.5" />
            Print Sticker
          </Button>
          <Button variant="outline" size="sm" onClick={handleCopyPayload}>
            {copied ? (
              <Check className="h-3.5 w-3.5 mr-1.5 text-emerald-500" />
            ) : (
              <Copy className="h-3.5 w-3.5 mr-1.5" />
            )}
            Copy JSON
          </Button>
        </div>
      </div>

      {/* QR Payload Preview */}
      <div className="space-y-1.5">
        <Label className="text-xs text-muted-foreground">QR Code Contents</Label>
        <pre className="text-[10px] bg-muted p-3 rounded-lg font-mono overflow-x-auto leading-relaxed">
          {payloadJson}
        </pre>
      </div>

      {/* How it works */}
      <div className="p-3 rounded-lg bg-muted/50 space-y-2">
        <p className="text-xs font-medium">This QR code:</p>
        <ol className="text-[11px] text-muted-foreground space-y-1 list-decimal list-inside">
          <li>Was originally generated by your ESP32 on first boot</li>
          <li>Is also visible at <code className="bg-muted px-1 rounded">192.168.4.1</code> when ESP32 is in AP mode</li>
          <li>Scan it in the dashboard app to register or re-register the device</li>
          <li>Configure WiFi/MQTT on the ESP32&apos;s AP page (WiFi: <span className="font-mono font-medium">{apSsid}</span>)</li>
          <li>After WiFi config, ESP32 connects and starts sending data!</li>
        </ol>
      </div>
    </div>
  );
}
